FROM azul/zulu-openjdk-alpine:11
RUN apk add curl jq
WORKDIR C:/Testcases_automation/automation
COPY target/selenium-docker.jar selenium-docker.jar
COPY target/selenium-docker-tests.jar selenium-docker-tests.jar
COPY target/libs libs 
COPY testng.xml testng.xml
#ENTRYPOINT java -cp selenium-docker.jar:selenium-docker-tests.jar:libs/* -DBROWSER=$BROWSER -DHUB_HOST=$HUB_HOST org.testng.TestNG $MODULE
ADD healthcheck.sh healthcheck.sh
ENTRYPOINT sh healthcheck.sh